### ISSUE TITLE
Serial number as uniq rather than in the name?

### ISSUE THREAD

**Issue by jgeumlek** [cvuchener/steamcontroller-linux-kernel#4]
From [this documenation](https://www.kernel.org/doc/htmldocs/device-drivers/API-struct-input-dev.html), the `uniq` field is

> ```
>  unique identification code for the device (if device has it)
> ```

This seems like a better place for the serial number, but I'm no expert on these conventions. The only other place I've come across `uniq` in my limited experience is in the bluetooth addresses for bluetooth input devices.

**Comment by cvuchener** [comment]
Yes, I think you are right.

I wrote this driver for testing and showing what I knew of the Steam Controller protocol, you may prefer to use my user-space driver instead (https://github.com/cvuchener/input-scripts), it is more complex but it allows the versatility that Steam Controller was designed for.

I will fix this, it is easy and makes a lot of sense, but if you have a real interest in a kernel driver for the Steam Controller, you should consider forking it.

**Comment by cvuchener** [comment]
Should be fixed by 566be8b.

**Comment by jgeumlek** [comment]
Thanks.

I have my own [user-space gamepad mapping framework](https://github.com/jgeumlek/MoltenGamepad) I've been playing with for personal use, and this kernel driver lets me avoid mucking around with USB internals.

These two nitpicks didn't seem worthy of a fork, and I can't imagine much more I desire from a kernel driver than just having all the events exposed like this.
