### ISSUE TITLE
Invert Y Axes

### ISSUE THREAD

**Issue by jgeumlek** [cvuchener/steamcontroller-linux-kernel#5]
As per [linux gamepad conventions](https://www.kernel.org/doc/Documentation/input/gamepad.txt), the y-axis is defined to have positive values at the bottom. This driver reports the reverse, with positive values at the top.

This inversion applies to both touch pads and the thumb stick.

**Comment by cvuchener** [comment]
Fixed in 6c807fc although there is a lot of other problems with the Steam Controller and these gamepad conventions.

**Comment by jgeumlek** [comment]
Yes, like the extra stick click event, the pads vs. two sticks, and the trigger axes. However, those seem reasonable given the uniqueness of this controller.

I linked that page mostly as an easy show this wasn't a substanceless nitpick. Most controllers I've used, event those that don't match the "gamepad API" above still follow the above y-axis convention.
